baseURL = 'http://emer.dev/'
languageCode = 'en-us'
theme = "anatole"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
title = "Mark's Github Page"
author = "Mark E. Anderson"
profilePicture = "https://secure.gravatar.com/avatar/840683939663de99dc03b639ee335691"

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/markemer/"

    [[params.socialIcons]]
    icon = "fab fa-github-square"
    title = "Github"
    url = "https://github.com/markemer"

    [[params.socialIcons]]
    icon = "fab fa-bluesky"
    title = "BlueSky"
    url = "https://bsky.app/profile/emer.net"

    [[params.socialIcons]]
    icon = "fab fa-mastodon"
    title = "Mastodon"
    url = "https://social.treehouse.systems/@markemer"

    [[params.socialIcons]]
    icon = "fab fa-square-threads"
    title = "Threads"
    url = "https://threads.net/mark.emer"

    [[params.socialIcons]]
    icon = "fab fa-square-instagram"
    title = "Instagram"
    url = "https://www.instagram.com/mark.emer"

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    # [[menu.main]]
    # name = "Starred"
    # indentifier = "starred"
    # weight = 100
    # url = "/starred"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
