baseURL = 'http://github.emer.net/'
languageCode = 'en-us'
theme = "anatole"

[params]
title = "Mark's Github Page"
author = "Mark E. Anderson"
profilePicture = "https://secure.gravatar.com/avatar/840683939663de99dc03b639ee335691"

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/markemer/"

    [[params.socialIcons]]
    icon = "fab fa-github-square"
    title = "Github"
    url = "https://github.com/markemer"

    [[params.socialIcons]]
    icon = "fab fa-twitter-square"
    title = "Twitter"
    url = "https://twitter.com/markemer"

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"
