baseURL = 'http://github.emer.net/'
languageCode = 'en-us'
title = "Mark's Github Page"
theme = "ananke"

[params]
author = "Mark E. Anderson"
twitter = "https://twitter.com/markemer"
github = "https://github.com/markemer"
linkedin = "https://www.linkedin.com/in/markemer/"
